AWSTemplateFormatVersion: '2010-09-09'
Description: >
  AWS CloudFormation template to provision a VPC, subnets, route tables, and security groups for the COLL production environment in eu-west-1.

Parameters:
  VpcCidr:
    Type: String
    Default: 10.0.192.0/20
    Description: CIDR block for the VPC
  AppDataSubnetACidr:
    Type: String
    Default: 10.0.192.0/24
    Description: CIDR block for appdata subnet A
  AppDataSubnetBCidr:
    Type: String
    Default: 10.0.193.0/24
    Description: CIDR block for appdata subnet B
  AppDataSubnetCCidr:
    Type: String
    Default: 10.0.194.0/24
    Description: CIDR block for appdata subnet C
  OfficePresentationSubnetACidr:
    Type: String
    Default: 10.0.195.0/24
    Description: CIDR block for office presentation subnet A
  OfficePresentationSubnetBCidr:
    Type: String
    Default: 10.0.196.0/24
    Description: CIDR block for office presentation subnet B
  OfficePresentationSubnetCCidr:
    Type: String
    Default: 10.0.197.0/24
    Description: CIDR block for office presentation subnet C
  InternetPresentationSubnetACidr:
    Type: String
    Default: 10.0.198.0/24
    Description: CIDR block for internet presentation subnet A
  InternetPresentationSubnetBCidr:
    Type: String
    Default: 10.0.199.0/24
    Description: CIDR block for internet presentation subnet B
  InternetPresentationSubnetCCidr:
    Type: String
    Default: 10.0.200.0/24
    Description: CIDR block for internet presentation subnet C

  # IAM Role Parameters
  COLLPrdReadRoleName:
    Type: String
    Default: COLL-prd-read-role
    Description: Name of the IAM role for read-only access in COLL production
  COLLPrdWriteRoleName:
    Type: String
    Default: COLL-prd-write-role
    Description: Name of the IAM role for write access in COLL production
  COLLPrdReadRoleTrustedAccounts:
    Type: CommaDelimitedList
    Default: "arn:aws:iam::481665121350:root"
    Description: List of AWS account ARNs allowed to assume the read-only role
  COLLPrdWriteRoleTrustedAccounts:
    Type: CommaDelimitedList
    Default: "arn:aws:iam::481665121350:root"
    Description: List of AWS account ARNs allowed to assume the write role

Resources:
  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref vpcCOLLprdEuw101
      InternetGatewayId: !Ref InternetGateway
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: coll-prd-internet-gateway

  vpcCOLLprdEuw101:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.192.0/20
      Tags:
        - Key: Name
          Value: vpc-COLL-prd-euw1-01

  snAppdataEuw1a:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref vpcCOLLprdEuw101
      CidrBlock: 10.0.192.0/24
      Tags:
        - Key: Name
          Value: sn-appdata-euw1a

  snAppdataEuw1b:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref vpcCOLLprdEuw101
      CidrBlock: 10.0.193.0/24
      Tags:
        - Key: Name
          Value: sn-appdata-euw1b

  snAppdataEuw1c:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref vpcCOLLprdEuw101
      CidrBlock: 10.0.194.0/24
      Tags:
        - Key: Name
          Value: sn-appdata-euw1c

  snOfficepresentationEuw1a:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref vpcCOLLprdEuw101
      CidrBlock: 10.0.195.0/24
      Tags:
        - Key: Name
          Value: sn-officepresentation-euw1a

  snOfficepresentationEuw1b:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref vpcCOLLprdEuw101
      CidrBlock: 10.0.196.0/24
      Tags:
        - Key: Name
          Value: sn-officepresentation-euw1b

  snOfficepresentationEuw1c:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref vpcCOLLprdEuw101
      CidrBlock: 10.0.197.0/24
      Tags:
        - Key: Name
          Value: sn-officepresentation-euw1c

  snInternetpresentationEuw1a:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref vpcCOLLprdEuw101
      CidrBlock: 10.0.198.0/24
      Tags:
        - Key: Name
          Value: sn-internetpresentation-euw1a

  snInternetpresentationEuw1b:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref vpcCOLLprdEuw101
      CidrBlock: 10.0.199.0/24
      Tags:
        - Key: Name
          Value: sn-internetpresentation-euw1b

  snInternetpresentationEuw1c:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref vpcCOLLprdEuw101
      CidrBlock: 10.0.200.0/24
      Tags:
        - Key: Name
          Value: sn-internetpresentation-euw1c

  rtbCollPrdCommonEuw1:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref vpcCOLLprdEuw101
      Tags:
        - Key: Name
          Value: rtb-coll-prd-common-euw1

  rtbCollPrdCommonEuw1AssocAppdataEuw1a:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref rtbCollPrdCommonEuw1
      SubnetId: !Ref snAppdataEuw1a

  rtbCollPrdCommonEuw1AssocAppdataEuw1b:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref rtbCollPrdCommonEuw1
      SubnetId: !Ref snAppdataEuw1b

  rtbCollPrdCommonEuw1AssocAppdataEuw1c:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref rtbCollPrdCommonEuw1
      SubnetId: !Ref snAppdataEuw1c

  rtbCollPrdCommonEuw1AssocOfficepresentationEuw1a:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref rtbCollPrdCommonEuw1
      SubnetId: !Ref snOfficepresentationEuw1a

  rtbCollPrdCommonEuw1AssocOfficepresentationEuw1b:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref rtbCollPrdCommonEuw1
      SubnetId: !Ref snOfficepresentationEuw1b

  rtbCollPrdCommonEuw1AssocOfficepresentationEuw1c:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref rtbCollPrdCommonEuw1
      SubnetId: !Ref snOfficepresentationEuw1c

  rtbCollPrdCommonEuw1AssocInternetpresentationEuw1a:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref rtbCollPrdCommonEuw1
      SubnetId: !Ref snInternetpresentationEuw1a

  rtbCollPrdCommonEuw1AssocInternetpresentationEuw1b:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref rtbCollPrdCommonEuw1
      SubnetId: !Ref snInternetpresentationEuw1b

  rtbCollPrdCommonEuw1AssocInternetpresentationEuw1c:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref rtbCollPrdCommonEuw1
      SubnetId: !Ref snInternetpresentationEuw1c

  rtbCollPrdCommonEuw1Route10080020:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref rtbCollPrdCommonEuw1
      DestinationCidrBlock: 10.0.80.0/20
      GatewayId: !Ref InternetGateway

  # baseline security groups
  sgAzureArc:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Azure Arc outbound
      VpcId: !Ref vpcCOLLprdEuw101
      Tags:
        - Key: Name
          Value: sg-azure-arc

  sgAzureMonitor:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Azure Monitor outbound
      VpcId: !Ref vpcCOLLprdEuw101
      Tags:
        - Key: Name
          Value: sg-azure-monitor

  sgMicrosoftDefender:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Microsoft Defender outbound
      VpcId: !Ref vpcCOLLprdEuw101
      Tags:
        - Key: Name
          Value: sg-microsoft-defender

  sgDatadog:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Data Dog outbound
      VpcId: !Ref vpcCOLLprdEuw101
      Tags:
        - Key: Name
          Value: sg-datadog

  sgQualys:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Qualys SaaS service
      VpcId: !Ref vpcCOLLprdEuw101
      Tags:
        - Key: Name
          Value: sg-qualys

  sgSentinelSyslog:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Sentinel syslog
      VpcId: !Ref vpcCOLLprdEuw101
      Tags:
        - Key: Name
          Value: sg-sentinel-syslog

  sgProdDomainControllers:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Prod Domain Controllers (bidirectional)
      VpcId: !Ref vpcCOLLprdEuw101
      Tags:
        - Key: Name
          Value: sg-prod-domain-controllers

  sgProdCertAuthority:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Prod Cert Authority (bidirectional)
      VpcId: !Ref vpcCOLLprdEuw101
      Tags:
        - Key: Name
          Value: sg-prod-cert-authority

  sgHttps:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: HTTPS inbound/outbound
      VpcId: !Ref vpcCOLLprdEuw101
      Tags:
        - Key: Name
          Value: sg-https

  # PRD IAM Roles
  COLLPrdReadRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref COLLPrdReadRoleName
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Ref COLLPrdReadRoleTrustedAccounts
            Action:
              - sts:AssumeRole

  COLLPrdWriteRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref COLLPrdWriteRoleName
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Ref COLLPrdWriteRoleTrustedAccounts
            Action:
              - sts:AssumeRole

Outputs:
  VpcId:
    Value: !Ref vpcCOLLprdEuw101
  RouteTableId:
    Value: !Ref rtbCollPrdCommonEuw1
  COLLPrdReadRoleArn:
    Description: ARN of the COLL production read-only IAM role
    Value: !GetAtt COLLPrdReadRole.Arn
  COLLPrdWriteRoleArn:
    Description: ARN of the COLL production write IAM role
    Value: !GetAtt COLLPrdWriteRole.Arn
