AWSTemplateFormatVersion: '2010-09-09'
Description: >
  AWS CloudFormation template to provision a VPC, subnets, route tables, and security groups for the COMM production environment in eu-west-1.

Parameters:
  VpcCidr:
    Type: String
    Default: 10.0.208.0/20
    Description: CIDR block for the VPC
  AppDataSubnetACidr:
    Type: String
    Default: 10.0.208.0/24
    Description: CIDR block for appdata subnet A
  AppDataSubnetBCidr:
    Type: String
    Default: 10.0.209.0/24
    Description: CIDR block for appdata subnet B
  AppDataSubnetCCidr:
    Type: String
    Default: 10.0.210.0/24
    Description: CIDR block for appdata subnet C
  OfficePresentationSubnetACidr:
    Type: String
    Default: 10.0.211.0/24
    Description: CIDR block for office presentation subnet A
  OfficePresentationSubnetBCidr:
    Type: String
    Default: 10.0.212.0/24
    Description: CIDR block for office presentation subnet B
  OfficePresentationSubnetCCidr:
    Type: String
    Default: 10.0.213.0/24
    Description: CIDR block for office presentation subnet C
  InternetPresentationSubnetACidr:
    Type: String
    Default: 10.0.214.0/24
    Description: CIDR block for internet presentation subnet A
  InternetPresentationSubnetBCidr:
    Type: String
    Default: 10.0.215.0/24
    Description: CIDR block for internet presentation subnet B
  InternetPresentationSubnetCCidr:
    Type: String
    Default: 10.0.216.0/24
    Description: CIDR block for internet presentation subnet C

  # IAM Role Parameters
  COMMPrdReadRoleName:
    Type: String
    Default: COMM-prd-read-role
    Description: Name of the IAM role for read-only access in COMM production
  COMMPrdWriteRoleName:
    Type: String
    Default: COMM-prd-write-role
    Description: Name of the IAM role for write access in COMM production
  COMMPrdReadRoleTrustedAccounts:
    Type: CommaDelimitedList
    Default: "arn:aws:iam::481665121350:root"
    Description: List of AWS account ARNs allowed to assume the read-only role
  COMMPrdWriteRoleTrustedAccounts:
    Type: CommaDelimitedList
    Default: "arn:aws:iam::481665121350:root"
    Description: List of AWS account ARNs allowed to assume the write role

Resources:
  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref vpcCOMMprdEuw101
      InternetGatewayId: !Ref InternetGateway
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: comm-prd-internet-gateway

  vpcCOMMprdEuw101:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.208.0/20
      Tags:
        - Key: Name
          Value: vpc-COMM-prd-euw1-01

  snAppdataEuw1a:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref vpcCOMMprdEuw101
      CidrBlock: 10.0.208.0/24
      Tags:
        - Key: Name
          Value: sn-appdata-euw1a

  snAppdataEuw1b:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref vpcCOMMprdEuw101
      CidrBlock: 10.0.209.0/24
      Tags:
        - Key: Name
          Value: sn-appdata-euw1b

  snAppdataEuw1c:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref vpcCOMMprdEuw101
      CidrBlock: 10.0.210.0/24
      Tags:
        - Key: Name
          Value: sn-appdata-euw1c

  snOfficepresentationEuw1a:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref vpcCOMMprdEuw101
      CidrBlock: 10.0.211.0/24
      Tags:
        - Key: Name
          Value: sn-officepresentation-euw1a

  snOfficepresentationEuw1b:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref vpcCOMMprdEuw101
      CidrBlock: 10.0.212.0/24
      Tags:
        - Key: Name
          Value: sn-officepresentation-euw1b

  snOfficepresentationEuw1c:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref vpcCOMMprdEuw101
      CidrBlock: 10.0.213.0/24
      Tags:
        - Key: Name
          Value: sn-officepresentation-euw1c

  snInternetpresentationEuw1a:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref vpcCOMMprdEuw101
      CidrBlock: 10.0.214.0/24
      Tags:
        - Key: Name
          Value: sn-internetpresentation-euw1a

  snInternetpresentationEuw1b:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref vpcCOMMprdEuw101
      CidrBlock: 10.0.215.0/24
      Tags:
        - Key: Name
          Value: sn-internetpresentation-euw1b

  snInternetpresentationEuw1c:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref vpcCOMMprdEuw101
      CidrBlock: 10.0.216.0/24
      Tags:
        - Key: Name
          Value: sn-internetpresentation-euw1c

  rtbCommPrdCommonEuw1:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref vpcCOMMprdEuw101
      Tags:
        - Key: Name
          Value: rtb-comm-prd-common-euw1

  rtbCommPrdCommonEuw1AssocAppdataEuw1a:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref rtbCommPrdCommonEuw1
      SubnetId: !Ref snAppdataEuw1a

  rtbCommPrdCommonEuw1AssocAppdataEuw1b:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref rtbCommPrdCommonEuw1
      SubnetId: !Ref snAppdataEuw1b

  rtbCommPrdCommonEuw1AssocAppdataEuw1c:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref rtbCommPrdCommonEuw1
      SubnetId: !Ref snAppdataEuw1c

  rtbCommPrdCommonEuw1AssocOfficepresentationEuw1a:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref rtbCommPrdCommonEuw1
      SubnetId: !Ref snOfficepresentationEuw1a

  rtbCommPrdCommonEuw1AssocOfficepresentationEuw1b:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref rtbCommPrdCommonEuw1
      SubnetId: !Ref snOfficepresentationEuw1b

  rtbCommPrdCommonEuw1AssocOfficepresentationEuw1c:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref rtbCommPrdCommonEuw1
      SubnetId: !Ref snOfficepresentationEuw1c

  rtbCommPrdCommonEuw1AssocInternetpresentationEuw1a:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref rtbCommPrdCommonEuw1
      SubnetId: !Ref snInternetpresentationEuw1a

  rtbCommPrdCommonEuw1AssocInternetpresentationEuw1b:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref rtbCommPrdCommonEuw1
      SubnetId: !Ref snInternetpresentationEuw1b

  rtbCommPrdCommonEuw1AssocInternetpresentationEuw1c:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref rtbCommPrdCommonEuw1
      SubnetId: !Ref snInternetpresentationEuw1c

  rtbCommPrdCommonEuw1Route10096020:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref rtbCommPrdCommonEuw1
      DestinationCidrBlock: 10.0.96.0/20
      GatewayId: !Ref InternetGateway

  # baseline security groups
  sgAzureArc:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Azure Arc outbound
      VpcId: !Ref vpcCOMMprdEuw101
      Tags:
        - Key: Name
          Value: sg-azure-arc

  sgAzureMonitor:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Azure Monitor outbound
      VpcId: !Ref vpcCOMMprdEuw101
      Tags:
        - Key: Name
          Value: sg-azure-monitor

  sgMicrosoftDefender:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Microsoft Defender outbound
      VpcId: !Ref vpcCOMMprdEuw101
      Tags:
        - Key: Name
          Value: sg-microsoft-defender

  sgDatadog:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Data Dog outbound
      VpcId: !Ref vpcCOMMprdEuw101
      Tags:
        - Key: Name
          Value: sg-datadog

  sgQualys:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Qualys SaaS service
      VpcId: !Ref vpcCOMMprdEuw101
      Tags:
        - Key: Name
          Value: sg-qualys

  sgSentinelSyslog:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Sentinel syslog
      VpcId: !Ref vpcCOMMprdEuw101
      Tags:
        - Key: Name
          Value: sg-sentinel-syslog

  sgProdDomainControllers:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Prod Domain Controllers (bidirectional)
      VpcId: !Ref vpcCOMMprdEuw101
      Tags:
        - Key: Name
          Value: sg-prod-domain-controllers

  sgProdCertAuthority:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Prod Cert Authority (bidirectional)
      VpcId: !Ref vpcCOMMprdEuw101
      Tags:
        - Key: Name
          Value: sg-prod-cert-authority

  sgHttps:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: HTTPS inbound/outbound
      VpcId: !Ref vpcCOMMprdEuw101
      Tags:
        - Key: Name
          Value: sg-https

  # PRD IAM Roles
  COMMPrdReadRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref COMMPrdReadRoleName
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Ref COMMPrdReadRoleTrustedAccounts
            Action:
              - sts:AssumeRole

  COMMPrdWriteRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref COMMPrdWriteRoleName
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Ref COMMPrdWriteRoleTrustedAccounts
            Action:
              - sts:AssumeRole

Outputs:
  VpcId:
    Value: !Ref vpcCOMMprdEuw101
  RouteTableId:
    Value: !Ref rtbCommPrdCommonEuw1
  COMMPrdReadRoleArn:
    Description: ARN of the COMM production read-only IAM role
    Value: !GetAtt COMMPrdReadRole.Arn
  COMMPrdWriteRoleArn:
    Description: ARN of the COMM production write IAM role
    Value: !GetAtt COMMPrdWriteRole.Arn
