<<<<<<< HEAD
name: OIDC assume test
=======
﻿name: OIDC assume test
>>>>>>> 5e88ad9 (Add OIDC assume test workflow)
on:
  workflow_dispatch:

jobs:
  assume:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS via OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Verify caller identity
        run: aws sts get-caller-identity
