name: OIDC assume test
on:
  workflow_dispatch:

jobs:
 assume:
  runs-on: ubuntu-latest
  steps:
   - name: Configure AWS via OIDC
    uses: aws-actions/configure-aws-credentials@v2
    with:
     role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
     aws-region: ${{ secrets.AWS_REGION }}

      - name: Verify caller identity
        run: aws sts get-caller-identity --output json
